[metadata]
  name = "stream_debug"

[global]
  plan = "discovery"
  case = "stream"
  total_instances = 41
  builder = "docker:go"
  runner = "local:docker"

[global.run.test_params]
  replication = "1"
  regions = '["Global"]'
  conn_per_peer = "10"

[[groups]]
  id = "providers"
   [groups.instances]
    count = 40

[[groups]]
  id = "clients"
  [groups.instances]
    count = 1
